# Generated by Django 4.2.3 on 2023-07-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_beverages_nonveg_vegitarian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Vegitarian',
        ),
        migrations.AlterField(
            model_name='beverages',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='beverages',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nonveg',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='nonveg',
            name='price',
            field=models.IntegerField(),
        ),
    ]
