# Generated by Django 4.2.3 on 2023-07-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
