# Generated by Django 4.2.3 on 2023-07-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beverages',
        ),
        migrations.DeleteModel(
            name='Nonveg',
        ),
        migrations.DeleteModel(
            name='Vegetarian',
        ),
    ]
