# Generated by Django 4.2.3 on 2023-07-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_beverages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beverages',
        ),
    ]
