# Generated by Django 4.2.3 on 2023-07-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_cart_beverages_remove_cart_nonveg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
