# Generated by Django 4.2.3 on 2023-07-18 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_delete_cart'),
        ('customer', '0003_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='cart', max_length=100)),
                ('Beverages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.beverages')),
                ('Nonveg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.nonveg')),
                ('Vegetarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vegetarian')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
