# Generated by Django 4.2.3 on 2023-07-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
