# Generated by Django 4.2.3 on 2023-07-19 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('status', models.CharField(choices=[('deliverd', 'delivered'), ('order placed', 'order placed'), ('cancel', 'cancel'), ('out for delivery', 'out for delivery'), ('shipped', 'shipped')], default='order placed', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('foods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.foods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
